services:
  
  app-builder:
    image: node:18-alpine
    command: sh -c "npm install && npm run app:watch"
    working_dir: /app
    volumes:
      - ./:/app
      - dist:/app/dist
      - node_modules:/app/node_modules
  
  server-builder:
    image: node:18-alpine
    command: sh -c "npm install && npm run server:watch"
    working_dir: /app
    volumes:
      - ./:/app
      - dist:/app/dist
      - node_modules:/app/node_modules
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
          - db:/var/lib/postgresql/data
  
  server:
    image: node:18-alpine
    command: sh -c "npm run server:start-dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - dist:/app/dist
      - node_modules:/app/node_modules
    depends_on:
      - app-builder
      - server-builder
      - db

volumes:
  dist:
  node_modules:
  db:
