services:
  app-builder:
    image: node:18-alpine
    command: sh -c "npm install && npm run app:watch"
    working_dir: /app
    volumes:
      - ./:/app
      - dist:/app/dist
      - node_modules:/app/node_modules
  server-builder:
    image: node:18-alpine
    command: sh -c "npm install && npm run server:watch"
    working_dir: /app
    volumes:
      - ./:/app
      - dist:/app/dist
      - node_modules:/app/node_modules
  server:
    image: node:18-alpine
    command: sh -c "npm run server:start-dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - dist:/app/dist
      - node_modules:/app/node_modules
    depends_on:
      - app-builder
      - server-builder

volumes:
  dist:
  node_modules:
